// This file was generated by counterfeiter
package fakes

import (
	"bufio"
	"io"
	"net"
	"net/url"
	"sync"

	"github.com/cloudfoundry-incubator/garden/client/connection"
	"github.com/tedsuo/rata"
)

type FakeHijacker struct {
	HijackStub        func(handler string, body io.Reader, params rata.Params, query url.Values, contentType string) (net.Conn, *bufio.Reader, error)
	hijackMutex       sync.RWMutex
	hijackArgsForCall []struct {
		handler     string
		body        io.Reader
		params      rata.Params
		query       url.Values
		contentType string
	}
	hijackReturns struct {
		result1 net.Conn
		result2 *bufio.Reader
		result3 error
	}
}

func (fake *FakeHijacker) Hijack(handler string, body io.Reader, params rata.Params, query url.Values, contentType string) (net.Conn, *bufio.Reader, error) {
	fake.hijackMutex.Lock()
	fake.hijackArgsForCall = append(fake.hijackArgsForCall, struct {
		handler     string
		body        io.Reader
		params      rata.Params
		query       url.Values
		contentType string
	}{handler, body, params, query, contentType})
	fake.hijackMutex.Unlock()
	if fake.HijackStub != nil {
		return fake.HijackStub(handler, body, params, query, contentType)
	} else {
		return fake.hijackReturns.result1, fake.hijackReturns.result2, fake.hijackReturns.result3
	}
}

func (fake *FakeHijacker) HijackCallCount() int {
	fake.hijackMutex.RLock()
	defer fake.hijackMutex.RUnlock()
	return len(fake.hijackArgsForCall)
}

func (fake *FakeHijacker) HijackArgsForCall(i int) (string, io.Reader, rata.Params, url.Values, string) {
	fake.hijackMutex.RLock()
	defer fake.hijackMutex.RUnlock()
	return fake.hijackArgsForCall[i].handler, fake.hijackArgsForCall[i].body, fake.hijackArgsForCall[i].params, fake.hijackArgsForCall[i].query, fake.hijackArgsForCall[i].contentType
}

func (fake *FakeHijacker) HijackReturns(result1 net.Conn, result2 *bufio.Reader, result3 error) {
	fake.HijackStub = nil
	fake.hijackReturns = struct {
		result1 net.Conn
		result2 *bufio.Reader
		result3 error
	}{result1, result2, result3}
}

var _ connection.Hijacker = new(FakeHijacker)
