// Code generated by protoc-gen-gogo.
// source: attach.proto
// DO NOT EDIT!

/*
Package warden is a generated protocol buffer package.

It is generated from these files:
	attach.proto
	capacity.proto
	copy_in.proto
	copy_out.proto
	create.proto
	destroy.proto
	echo.proto
	environment_variable.proto
	error.proto
	info.proto
	limit_bandwidth.proto
	limit_cpu.proto
	limit_disk.proto
	limit_memory.proto
	list.proto
	message.proto
	net_in.proto
	net_out.proto
	ping.proto
	process_payload.proto
	property.proto
	resource_limits.proto
	run.proto
	stop.proto

It has these top-level messages:
	AttachRequest
*/
package warden

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type AttachRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	ProcessId        *uint32 `protobuf:"varint,2,req,name=process_id" json:"process_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AttachRequest) Reset()         { *m = AttachRequest{} }
func (m *AttachRequest) String() string { return proto.CompactTextString(m) }
func (*AttachRequest) ProtoMessage()    {}

func (m *AttachRequest) GetHandle() string {
	if m != nil && m.Handle != nil {
		return *m.Handle
	}
	return ""
}

func (m *AttachRequest) GetProcessId() uint32 {
	if m != nil && m.ProcessId != nil {
		return *m.ProcessId
	}
	return 0
}

func init() {
}
