// Code generated by protoc-gen-gogo.
// source: get_property.proto
// DO NOT EDIT!

package garden

import proto "github.com/gogo/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type GetPropertyRequest struct {
	Handle           *string `protobuf:"bytes,1,opt,name=handle" json:"handle,omitempty"`
	Key              *string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetPropertyRequest) Reset()         { *m = GetPropertyRequest{} }
func (m *GetPropertyRequest) String() string { return proto.CompactTextString(m) }
func (*GetPropertyRequest) ProtoMessage()    {}

func (m *GetPropertyRequest) GetHandle() string {
	if m != nil && m.Handle != nil {
		return *m.Handle
	}
	return ""
}

func (m *GetPropertyRequest) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

type GetPropertyResponse struct {
	Value            *string `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetPropertyResponse) Reset()         { *m = GetPropertyResponse{} }
func (m *GetPropertyResponse) String() string { return proto.CompactTextString(m) }
func (*GetPropertyResponse) ProtoMessage()    {}

func (m *GetPropertyResponse) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
}
