// Code generated by protoc-gen-gogo.
// source: list.proto
// DO NOT EDIT!

package warden

import proto "code.google.com/p/gogoprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ListRequest struct {
	Properties       []*Property `protobuf:"bytes,1,rep,name=properties" json:"properties,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}

func (m *ListRequest) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

type ListResponse struct {
	Handles          []string `protobuf:"bytes,1,rep,name=handles" json:"handles,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}

func (m *ListResponse) GetHandles() []string {
	if m != nil {
		return m.Handles
	}
	return nil
}

func init() {
}
