// Code generated by protoc-gen-gogo.
// source: remove_property.proto
// DO NOT EDIT!

package garden

import proto "github.com/gogo/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type RemovePropertyRequest struct {
	Handle           *string `protobuf:"bytes,1,opt,name=handle" json:"handle,omitempty"`
	Key              *string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RemovePropertyRequest) Reset()         { *m = RemovePropertyRequest{} }
func (m *RemovePropertyRequest) String() string { return proto.CompactTextString(m) }
func (*RemovePropertyRequest) ProtoMessage()    {}

func (m *RemovePropertyRequest) GetHandle() string {
	if m != nil && m.Handle != nil {
		return *m.Handle
	}
	return ""
}

func (m *RemovePropertyRequest) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

type RemovePropertyResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RemovePropertyResponse) Reset()         { *m = RemovePropertyResponse{} }
func (m *RemovePropertyResponse) String() string { return proto.CompactTextString(m) }
func (*RemovePropertyResponse) ProtoMessage()    {}

func init() {
}
