// Code generated by protoc-gen-gogo.
// source: set_property.proto
// DO NOT EDIT!

package garden

import proto "github.com/gogo/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type SetPropertyRequest struct {
	Handle           *string `protobuf:"bytes,1,opt,name=handle" json:"handle,omitempty"`
	Key              *string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetPropertyRequest) Reset()         { *m = SetPropertyRequest{} }
func (m *SetPropertyRequest) String() string { return proto.CompactTextString(m) }
func (*SetPropertyRequest) ProtoMessage()    {}

func (m *SetPropertyRequest) GetHandle() string {
	if m != nil && m.Handle != nil {
		return *m.Handle
	}
	return ""
}

func (m *SetPropertyRequest) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *SetPropertyRequest) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type SetPropertyResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetPropertyResponse) Reset()         { *m = SetPropertyResponse{} }
func (m *SetPropertyResponse) String() string { return proto.CompactTextString(m) }
func (*SetPropertyResponse) ProtoMessage()    {}

func init() {
}
