// Code generated by protoc-gen-gogo.
// source: stream_chunk.proto
// DO NOT EDIT!

package warden

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type StreamChunk struct {
	Content          []byte `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	EOF              *bool  `protobuf:"varint,2,opt" json:"EOF,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *StreamChunk) Reset()         { *m = StreamChunk{} }
func (m *StreamChunk) String() string { return proto.CompactTextString(m) }
func (*StreamChunk) ProtoMessage()    {}

func (m *StreamChunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *StreamChunk) GetEOF() bool {
	if m != nil && m.EOF != nil {
		return *m.EOF
	}
	return false
}

func init() {
}
