// Code generated by protoc-gen-gogo.
// source: tty.proto
// DO NOT EDIT!

package warden

import proto "code.google.com/p/gogoprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type TTY struct {
	WindowSize       *TTY_WindowSize `protobuf:"bytes,1,opt,name=window_size" json:"window_size,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *TTY) Reset()         { *m = TTY{} }
func (m *TTY) String() string { return proto.CompactTextString(m) }
func (*TTY) ProtoMessage()    {}

func (m *TTY) GetWindowSize() *TTY_WindowSize {
	if m != nil {
		return m.WindowSize
	}
	return nil
}

type TTY_WindowSize struct {
	Columns          *uint32 `protobuf:"varint,1,req,name=columns" json:"columns,omitempty"`
	Rows             *uint32 `protobuf:"varint,2,req,name=rows" json:"rows,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TTY_WindowSize) Reset()         { *m = TTY_WindowSize{} }
func (m *TTY_WindowSize) String() string { return proto.CompactTextString(m) }
func (*TTY_WindowSize) ProtoMessage()    {}

func (m *TTY_WindowSize) GetColumns() uint32 {
	if m != nil && m.Columns != nil {
		return *m.Columns
	}
	return 0
}

func (m *TTY_WindowSize) GetRows() uint32 {
	if m != nil && m.Rows != nil {
		return *m.Rows
	}
	return 0
}

func init() {
}
