#!/bin/bash
# vim: set ft=sh

set -e -x

go vet -mod vendor ./...
ginkgo -mod vendor -r -p --race --keep-going --nodes="${GINKGO_NODES:-8}" --fail-on-pending --randomize-suites --randomize-all-specs "$@"
